name: Sonar-workflow
on: workflow_dispatch
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Testing workflow
              run: echo "Workflow Works"
              